name: 'Install flutter'
description: 'install flutter'

runs:
  using: "composite"
  steps:
    - name: Install flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'
        channel: 'stable'
