name: Test 

on:
  push       

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/install-flutter

      - run: flutter pub get
      - run: flutter test
